language: python
python:
- '3.6'
- '2.7'
install: pip install tox codecov
script: make coverage
after_success: codecov
deploy:
  provider: pypi
  user: boxed
  password:
    secure: RIx54eu4Pxu4nDWNU8WCztI0POS9iPmIz4v4ClzkFIGR3N14sfK3V4OHnQMSI/3rY1KBbm4XRRoOpzLi52tHYI7B4FUzp0TSrWKjETqHgA2/ZJ4fCFyCYnD+loU4MKWHTcVfmlVKyhGIXxBTCX5T6ieUFcno455eE11PKQSo1gsK36uB5WMeW7E6hwAvn3b17PFLiMnpGq8rO3+QzU0WbLCRacKXGMuleqKMDGxvmDwZIz1Sk3RhPMY+EHXNYXFeBzCxjdlxf5ZwVFrQgqqni4C0et04xq680d81KbVdt9iqptdGr54d7Gl1S+ErVj7fwCkCrAFrcy3ui+e0TJofNefdn2i45PhDodoLC4tiT18Tx6ZA4AYPb9RkyTr5WUWIZ5KOaNqsZIxvo13pw4x5oTv8kf5MJ/pMF5MzY+Mx8+4hk7Box0t6V5OIWcm3vu4gIFDEWinKCKjmR3leP6kY/Nlc7M//jBcG1DJ3WajFIv7+eNe4kqPV2PHjN9SsxtlAWO1oqyV2pcWlmSPyIutIZy0jehHCxBEPvK05yq34fHV7JVQOcjIgi4IyyUgJ+Kfkf0E0TcTVvBkjE7FD01ekvI9jvlhwC20BvfWw+7b7iL8pTyQb1FqmgF5FkEIPugeDYR1pT19efrHbfSZtvv+eXV+UltSpQix1Jn9u+JqOxNE=
  on:
    python: 3.6
    tags: true
    repo: boxed/mutmut
